# Generated by Django 5.2.16 on 2026-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bookings_event_alter_bookings_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Event',
                'verbose_name_plural': 'Expired Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.event',),
        ),
    ]
