# Generated by Django 5.2.16 on 2026-07-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_expiredevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dnt',
            field=models.DateTimeField(),
        ),
    ]
